### ISSUE TITLE
Throwing error when importing react-csv

### ISSUE THREAD

**Issue by juampibermani** [react-csv/react-csv#142]
I'm having some trouble importing the package:
I installed the package using npm install
Then i use import { CSVLink } from "react-csv";
Then when i run npm start the process exits with this error:
```
Error: watch /myProyectPath/public ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1371:19)
    at Object.fs.watch (fs.js:1397:11)
    at createFsWatchInstance (/myProyectPath/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/myProyectPath/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/myProyectPath/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/myProyectPath/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/myProyectPath/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/myProyectPath/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:153:5)

```

It looks like there is a problem with fs. And for what i understand fs can't be used in react. I guess this package was built for using it in react.

Please help me!

**Comment by pradip8928** [comment]
you should fire this command to avoid this error:

npm install prop-types

It works for me
